# Generated by Django 5.2.15 on 2026-06-27 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gesture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('gesture_type', models.CharField(choices=[('static', 'Static'), ('dynamic', 'Dynamic')], default='static', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PredictionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_gesture', models.CharField(max_length=100)),
                ('confidence', models.FloatField()),
                ('landmark', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DatasetSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('landmark', models.JSONField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='samples/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gesture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vision.gesture')),
            ],
        ),
    ]
