# Generated by Django 5.2.15 on 2026-06-28 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vision', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicDatasetSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frames', models.JSONField()),
                ('frame_count', models.IntegerField(default=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gesture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vision.gesture')),
            ],
        ),
    ]
