# Generated by Django 5.2.15 on 2026-06-28 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vision', '0002_dynamicdatasetsample'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentenceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.TextField()),
                ('mode', models.CharField(choices=[('static', 'Static'), ('dynamic', 'Dynamic'), ('mixed', 'Mixed')], default='mixed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
